# Generated by Django 5.2.4 on 2025-08-24 08:06

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_productimage_reviewimage_delete_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewimage',
            name='link',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True),
        ),
    ]
