# Generated by Django 5.2.4 on 2025-08-11 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_category_description_alter_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_children', to='store.category'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('MoMo', 'Momo'), ('Tiền mặt', 'Cash'), ('VNPay', 'Vnpay')], default='Tiền mặt', max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('Đã chờ', 'Pending'), ('Thành công', 'Success'), ('Thất bại', 'Fail')], default='Đã chờ', max_length=50),
        ),
    ]
