# Generated by Django 5.2.4 on 2025-08-24 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_reviewimage_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='store.review'),
        ),
    ]
