# Generated by Django 5.2.4 on 2025-08-17 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_order_total_price_alter_conversation_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsreceiptdetail',
            name='goods_receipt',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.goodsreceipt'),
            preserve_default=False,
        ),
    ]
