# Generated by Django 5.2.4 on 2025-08-24 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_review_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Quản trị viên'), ('customer', 'Khách hàng'), ('manager', 'Quản lý'), ('staff', 'Nhân viên')], max_length=10),
        ),
    ]
