# Generated by Django 5.2.4 on 2025-08-12 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_payment_order_alter_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.supplier'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('MoMo', 'Momo'), ('Tiền mặt', 'Cash'), ('VNPay', 'Vnpay')], default='Tiền mặt', max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('Đã chờ', 'Pending'), ('Thành công', 'Success'), ('Thất bại', 'Fail')], default='Đã chờ', max_length=50),
        ),
    ]
