# Generated by Django 5.2.4 on 2025-08-25 09:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_loyaltypoint'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loyaltypoint',
            old_name='points',
            new_name='total_point',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Đã đặt hàng'), ('PAID', 'Đã thanh toán'), ('CANCELED', 'Đã huỷ')], default='PENDING', max_length=50),
        ),
        migrations.CreateModel(
            name='LoyaltyPointHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('point', models.IntegerField()),
                ('type', models.CharField(choices=[('EARN', 'Tích điểm'), ('REDEMP', 'Đổi điểm')], default='EARN', max_length=10)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
