# Generated by Django 5.2.4 on 2025-08-21 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_imageproduct'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ImageProduct',
            new_name='ProductImage',
        ),
    ]
