# Generated by Django 5.2.4 on 2025-08-25 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_rename_points_loyaltypoint_total_point_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('momo', 'MoMo'), ('cash', 'Tiền mặt'), ('vnpay', 'VNPay')], default='cash', max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Đã chờ'), ('success', 'Thành công'), ('fail', 'Thất bại')], default='pending', max_length=50),
        ),
    ]
