# Generated by Django 5.2.4 on 2025-08-25 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_payment_method_alter_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Đã đặt hàng'), ('PAID', 'Đã thanh toán'), ('SHIPPING', 'Đang giao hàng'), ('DELIVERED', 'Đã giao hàng'), ('CANCELED', 'Đã huỷ')], default='PENDING', max_length=50),
        ),
    ]
