# Generated by Django 5.2.4 on 2025-08-12 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_payment_method_alter_payment_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='tax',
            new_name='number_phone',
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('MoMo', 'Momo'), ('Tiền mặt', 'Cash'), ('VNPay', 'Vnpay')], default='Tiền mặt', max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('Đã chờ', 'Pending'), ('Thành công', 'Success'), ('Thất bại', 'Fail')], default='Đã chờ', max_length=50),
        ),
    ]
