# Generated by Django 5.2.4 on 2025-08-12 15:52

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_rename_tax_supplier_number_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='logo',
            field=cloudinary.models.CloudinaryField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('MoMo', 'Momo'), ('Tiền mặt', 'Cash'), ('VNPay', 'Vnpay')], default='Tiền mặt', max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('Đã chờ', 'Pending'), ('Thành công', 'Success'), ('Thất bại', 'Fail')], default='Đã chờ', max_length=50),
        ),
    ]
