# Generated by Django 5.2.4 on 2025-08-29 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_cart_cartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loyaltypointhistory',
            name='type',
            field=models.CharField(choices=[('EARN', 'Tích điểm'), ('REDEEM', 'Đổi điểm')], default='EARN', max_length=10),
        ),
    ]
