# Generated by Django 5.2.4 on 2025-08-29 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_alter_user_address_alter_user_avatar_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_date']},
        ),
    ]
