# Generated by Django 5.2.4 on 2025-09-04 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_alter_review_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_date']},
        ),
    ]
