# Generated by Django 5.2.4 on 2025-09-10 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_alter_review_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_parent',
        ),
    ]
