# Generated by Django 5.2.4 on 2025-09-11 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_remove_category_category_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('momo', 'MoMo'), ('cash', 'Tiền mặt'), ('vnpay', 'VNPay')], default='cash', max_length=50),
        ),
    ]
