# Generated by Django 5.2.4 on 2025-09-11 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='number_phone',
            field=models.CharField(default=123, max_length=11),
            preserve_default=False,
        ),
    ]
