# Generated by Django 5.2.4 on 2025-09-11 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_order_address_order_number_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='name_customer',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
