# Generated by Django 5.2.4 on 2025-09-15 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_alter_review_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'Giỏ hàng', 'verbose_name_plural': 'Giỏ hàng'},
        ),
        migrations.AlterModelOptions(
            name='cartitem',
            options={'verbose_name': 'Mục giỏ hàng', 'verbose_name_plural': 'Mục giỏ hàng'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Danh mục', 'verbose_name_plural': 'Danh mục'},
        ),
        migrations.AlterModelOptions(
            name='conversation',
            options={'verbose_name': 'Cuộc trò chuyện', 'verbose_name_plural': 'Cuộc trò chuyện'},
        ),
        migrations.AlterModelOptions(
            name='discount',
            options={'verbose_name': 'Mã giảm giá', 'verbose_name_plural': 'Mã giảm giá'},
        ),
        migrations.AlterModelOptions(
            name='goodsreceipt',
            options={'verbose_name': 'Phiếu nhập hàng', 'verbose_name_plural': 'Phiếu nhập hàng'},
        ),
        migrations.AlterModelOptions(
            name='goodsreceiptdetail',
            options={'verbose_name': 'Chi tiết phiếu nhập hàng', 'verbose_name_plural': 'Chi tiết phiếu nhập hàng'},
        ),
        migrations.AlterModelOptions(
            name='loyaltypoint',
            options={'verbose_name': 'Điểm thưởng', 'verbose_name_plural': 'Điểm thưởng'},
        ),
        migrations.AlterModelOptions(
            name='loyaltypointhistory',
            options={'verbose_name': 'Lịch sử điểm thưởng', 'verbose_name_plural': 'Lịch sử điểm thưởng'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'Tin nhắn', 'verbose_name_plural': 'Tin nhắn'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_date'], 'verbose_name': 'Đơn hàng', 'verbose_name_plural': 'Đơn hàng'},
        ),
        migrations.AlterModelOptions(
            name='orderdetail',
            options={'verbose_name': 'Chi tiết đơn hàng', 'verbose_name_plural': 'Chi tiết đơn hàng'},
        ),
        migrations.AlterModelOptions(
            name='otp',
            options={'verbose_name': 'Mã OTP', 'verbose_name_plural': 'Mã OTP'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'Thanh toán', 'verbose_name_plural': 'Thanh toán'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['id'], 'verbose_name': 'Sản phẩm', 'verbose_name_plural': 'Sản phẩm'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'Hình ảnh sản phẩm', 'verbose_name_plural': 'Hình ảnh sản phẩm'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_date'], 'verbose_name': 'Đánh giá', 'verbose_name_plural': 'Đánh giá'},
        ),
        migrations.AlterModelOptions(
            name='reviewimage',
            options={'verbose_name': 'Hình ảnh đánh giá', 'verbose_name_plural': 'Hình ảnh đánh giá'},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'verbose_name': 'Nhà cung cấp', 'verbose_name_plural': 'Nhà cung cấp'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Người dùng', 'verbose_name_plural': 'Người dùng'},
        ),
        migrations.AlterUniqueTogether(
            name='conversation',
            unique_together=set(),
        ),
    ]
