# Generated by Django 5.2.4 on 2025-09-18 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_alter_cart_options_alter_cartitem_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loyaltypointhistory',
            options={'ordering': ['-created_date'], 'verbose_name': 'Lịch sử điểm thưởng', 'verbose_name_plural': 'Lịch sử điểm thưởng'},
        ),
    ]
